import React, { Component } from "react";

export default class Hra extends Component {
  render() {
    return (
      <div className="scrollArea">
       <table className="table-bordered">
	<thead><tr><th></th><th>E2</th><th> =15 EE</th><th> =20 EE</th><th> =20 EE</th><th> =20 EE</th><th> =20 EE</th><th> =20 EE</th><th> =30 EE</th><th> =30 EE</th><th> =30 EE</th><th> =30 EE</th><th> =30 EE</th><th> =30 EE</th><th> =35 EE</th><th> =35 EE</th><th> =0 EE</th></tr></thead><tbody>
	 <tr><td>&nbsp;</td><td>&nbsp;</td><td>gestoden</td><td>gestoden</td><td>desogestrel</td><td>drospirenon</td><td>drospirenon</td><td>levonorgestrel</td><td>gestoden</td><td>desogestrel</td><td>dienogest</td><td>levonorgestrel</td><td>drospirenon</td><td>chlormadinoacetát</td><td>norgestimat</td><td>cyproteron</td><td>desogestrel</td></tr>
	 <tr><td>&nbsp;</td><td>&nbsp;</td><td>24+4</td><td>&nbsp;</td><td>&nbsp;</td><td>24+4</td><td>21/28</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>RG</td><td>&nbsp;</td><td>VIOLETTA</td><td>LINDYNETTE</td><td>NOVYNETTE</td><td>DAYLETTE</td><td>DAYLLA </td><td>&nbsp;</td><td>&nbsp;</td><td>REGULON</td><td>MISTRA</td><td>&nbsp;</td><td>MAITALON</td><td>BELARA</td><td>&nbsp;</td><td>&nbsp;</td><td>AZALIA</td></tr>
	 <tr><td>&nbsp;</td><td>&nbsp;</td><td>515</td><td>511 / 876</td><td>561</td><td>703 / 1149</td><td>777</td><td>&nbsp;</td><td>&nbsp;</td><td>561</td><td>672 / 1106</td><td>&nbsp;</td><td>549 / 980</td><td>768 / 1264</td><td>&nbsp;</td><td>&nbsp;</td><td>586</td></tr>
	 <tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>BAYER SCHERING</td><td>QLAIRA</td><td>MIRELLE</td><td>LOGEST</td><td>&nbsp;</td><td>YAZ</td><td>YASMINELLE </td><td>&nbsp;</td><td>FEMODEN</td><td>&nbsp;</td><td>JEANINE</td><td>MICROGYNON</td><td>YADINE</td><td>&nbsp;</td><td>&nbsp;</td><td>DIANE 35</td><td>&nbsp;</td></tr>
	 <tr><td>PHARMA</td><td>1069</td><td>598</td><td>587</td><td>&nbsp;</td><td>1032</td><td>1095</td><td>&nbsp;</td><td>519</td><td>&nbsp;</td><td>860</td><td>478</td><td>859</td><td>&nbsp;</td><td>&nbsp;</td><td>621</td><td>&nbsp;</td></tr>
	 <tr><td>2nd Brand </td><td>dienogest</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>ELOINE</td><td>BELANETTE </td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>MINISISTON</td><td>SYLVIANE </td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>Bayer</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>794</td><td>695</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>514</td><td>637</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>MSD</td><td>ZOELY</td><td>&nbsp;</td><td>&nbsp;</td><td>MERCILON</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>MARVELON</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>CERAZETTE</td></tr>
	 <tr><td>&nbsp;</td><td>1119</td><td>&nbsp;</td><td>&nbsp;</td><td>612</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>617</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>674</td></tr>
	 <tr><td>&nbsp;</td><td>nomegestrol</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>PFIZER</td><td>&nbsp;</td><td>MINESSE</td><td>HARMONET</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>LOETTE</td><td>MINULET</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>&nbsp;</td><td>&nbsp;</td><td>670</td><td>585</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>776</td><td>555</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>MEDICOM Int.</td><td>&nbsp;</td><td>&nbsp;</td><td>LUNAFEM</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>MINERVA</td><td>&nbsp;</td></tr>
	 <tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>484</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>494</td><td>&nbsp;</td></tr>
	 <tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>ZENTIVA</td><td>&nbsp;</td><td>&nbsp;</td><td>ARTIZIA</td><td>REGISHA</td><td>MYWY</td><td>SIDRETELLA</td><td>&nbsp;</td><td>&nbsp;</td><td>REGISHA</td><td>BONADEA</td><td>&nbsp;</td><td>SIDRETA</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>475</td><td>480</td><td>555</td><td>655</td><td>&nbsp;</td><td>&nbsp;</td><td>480</td><td>559</td><td>&nbsp;</td><td>655</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>HEATON</td><td>&nbsp;</td><td>NELYA</td><td>SUNYA</td><td>NATALYA</td><td>LUISEA</td><td>&nbsp;</td><td>&nbsp;</td><td>KATYA</td><td>ADELE</td><td>SIRMYA</td><td>EBELYA</td><td>&nbsp;</td><td>FLAYA</td><td>&nbsp;</td><td>VREYA</td><td>LAMYA</td></tr>
	 <tr><td>&nbsp;</td><td>&nbsp;</td><td>581</td><td>478</td><td>588</td><td>643</td><td>&nbsp;</td><td>&nbsp;</td><td>499</td><td>586</td><td>552</td><td>488</td><td>&nbsp;</td><td>703</td><td>&nbsp;</td><td>557</td><td>586</td></tr>
	 <tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>PHARMA SWISS</td><td>&nbsp;</td><td>&nbsp;</td><td>STODETTE</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>430</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>EXELTIS</td><td>&nbsp;</td><td>VONILLE</td><td>&nbsp;</td><td>&nbsp;</td><td>VELMARI</td><td>JANGEE 0,02</td><td>ASUMATE</td><td>&nbsp;</td><td>&nbsp;</td><td>DIENILLE</td><td>LEVERETTE</td><td>JANGEE 0,03</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>&nbsp;</td><td>&nbsp;</td><td>528</td><td>&nbsp;</td><td>&nbsp;</td><td>764</td><td>718</td><td>502</td><td>&nbsp;</td><td>&nbsp;</td><td>688</td><td>502</td><td>698</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>2nd Brand</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>DIECYCLEN</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>Exeltis</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>445</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>TEVA</td><td>&nbsp;</td><td>VIDETTE</td><td>&nbsp;</td><td>&nbsp;</td><td>VEYANNE</td><td>SOFTINELLE</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>VEREZANA</td><td>SEASONIQUE</td><td>SOFTINE</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>XYNIA</td></tr>
	 <tr><td>&nbsp;</td><td>&nbsp;</td><td>506</td><td>&nbsp;</td><td>&nbsp;</td><td>674</td><td>646</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>529</td><td>837</td><td>646</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>477</td></tr>
	 <tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>WH Pharma</td><td>&nbsp;</td><td>BIRGI</td><td>LUSIENNE</td><td>BELLVALYN</td><td>YOSEFINNE</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>AYREEN</td><td>&nbsp;</td><td>&nbsp;</td><td>CLORMETIN</td><td>&nbsp;</td><td>&nbsp;</td><td>EVELLIEN</td></tr>
	 <tr><td>&nbsp;</td><td>&nbsp;</td><td>520</td><td>458</td><td>479</td><td>673</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>670</td><td>&nbsp;</td><td>&nbsp;</td><td>704</td><td>&nbsp;</td><td>&nbsp;</td><td>488</td></tr>
	 <tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>SANDOZ</td><td>&nbsp;</td><td>TANIELLE</td><td>TANIELLE</td><td>STRELICIA</td><td>NYSSIELA</td><td>RHONYA 0,02</td><td>&nbsp;</td><td>TANIELLE</td><td>STRELICIA</td><td>FOXINETTE NEO</td><td>KHALISSIMA</td><td>RHONYA 0,03</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>DAISENETTE NEO</td></tr>
	 <tr><td>&nbsp;</td><td>&nbsp;</td><td>459</td><td>380</td><td>429</td><td>529</td><td>599</td><td>&nbsp;</td><td>450</td><td>429</td><td>599</td><td>380</td><td>599</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>439</td></tr>
	 <tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>STADA</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>SINELA</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>YANELA</td><td>LEANOVA</td><td>&nbsp;</td><td>BONISSA</td><td>&nbsp;</td><td>&nbsp;</td><td>DESOGESTREL</td></tr>
	 <tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>540</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>537</td><td>399</td><td>&nbsp;</td><td>553</td><td>&nbsp;</td><td>&nbsp;</td><td>STADA - 429</td></tr>
	 <tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>AV Medical</td><td>&nbsp;</td><td>&nbsp;</td><td>SAXI 0,02</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>SAXI 0,03</td><td>&nbsp;</td><td>STYLIA</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>MENYAN</td><td>&nbsp;</td><td>TORRI</td></tr>
	 <tr><td>Consulting</td><td>&nbsp;</td><td>&nbsp;</td><td>347</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>430</td><td>&nbsp;</td><td>380</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>390</td><td>&nbsp;</td><td>398</td></tr>
	 <tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>Actavis</td><td>&nbsp;</td><td>&nbsp;</td><td>INDIRETTE</td><td>&nbsp;</td><td>CLEONITA</td><td>CLEODETTE</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>SIENIMA</td><td>&nbsp;</td><td>CLEOSENSA</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>348</td><td>&nbsp;</td><td>497</td><td>399</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>567</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>EGIS</td><td>&nbsp;</td><td>DITINEL</td><td>GENTILION 0.02</td><td>&nbsp;</td><td>EMONA</td><td>FEMINEGI 0,02</td><td>&nbsp;</td><td>GENTILION 0,03</td><td>BELLVALYN</td><td>OMISSON</td><td>&nbsp;</td><td>FEMINEGI 0,03</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>&nbsp;</td><td>&nbsp;</td><td>512</td><td>416</td><td>&nbsp;</td><td>584</td><td>467</td><td>&nbsp;</td><td>299</td><td>485</td><td>497</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>VIVAX</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>AIDEE</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>488</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>GENERICON</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>PAOLETTA</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>496</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>GENERICS</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>MYLAZ</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>MYLINE</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>299</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>ARDEZ Pharma</td><td>&nbsp;</td><td>&nbsp;</td><td>MOYETE</td><td>&nbsp;</td><td>SUZIA</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>FLORETTE</td></tr>
	 <tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>343</td><td>&nbsp;</td><td>395</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>372</td></tr>
	 <tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>LITcon SE</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>MALOO</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>CALLETO</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>410</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>597</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>ADAMED CZECH REPUBLIC</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>AXIA DAILY 0,02</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>AXIA 0,03</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
	 <tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>377,84</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>392,55</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td></td></tr>
	</tbody></table>
      </div>
    );
  }
}
